//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEntityFrameWorkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public short isHand { get; set; }
        public string dateOf { get; set; }
        public int VisitorId { get; set; }
        public int BookId { get; set; }
    
        public virtual Visitor Visitor { get; set; }
        public virtual Book Book { get; set; }
    }
}
